
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public demo.TbReward TbReward {get; }
    public demo.Tbitem Tbitem {get; }
    public Tbhero Tbhero {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbReward = new demo.TbReward(loader("demo_tbreward"));
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        Tbhero = new Tbhero(loader("tbhero"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbReward.ResolveRef(this);
        Tbitem.ResolveRef(this);
        Tbhero.ResolveRef(this);
    }
}

}
