
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.game
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["values"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Values = new string[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Values[__index0++] = __v0; }   }
    }

    public static Item DeserializeItem(JSONNode _buf)
    {
        return new game.Item(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 参数列表
    /// </summary>
    public readonly string[] Values;
   
    public const int __ID__ = 954631087;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "values:" + Luban.StringUtil.CollectionToString(Values) + ","
        + "}";
    }
}
}

