
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.game
{
public partial class Tbconfig
{
    private readonly System.Collections.Generic.Dictionary<string, game.config> _dataMap;
    private readonly System.Collections.Generic.List<game.config> _dataList;
    
    public Tbconfig(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, game.config>(count);
        _dataList = new System.Collections.Generic.List<game.config>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            game.config _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.game.config.Deserializeconfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, game.config> DataMap => _dataMap;
    public System.Collections.Generic.List<game.config> DataList => _dataList;

    public game.config GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public game.config Get(string key) => _dataMap[key];
    public game.config this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

