
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.game
{
/// <summary>
/// 战斗内道具表
/// </summary>
public partial class TbItem
{
    private readonly System.Collections.Generic.Dictionary<string, game.Item> _dataMap;
    private readonly System.Collections.Generic.List<game.Item> _dataList;
    
    public TbItem(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, game.Item>(count);
        _dataList = new System.Collections.Generic.List<game.Item>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            game.Item _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.game.Item.DeserializeItem(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, game.Item> DataMap => _dataMap;
    public System.Collections.Generic.List<game.Item> DataList => _dataList;

    public game.Item GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public game.Item Get(string key) => _dataMap[key];
    public game.Item this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

