
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public demo.TbReward TbReward {get; }
    /// <summary>
    /// 目录下包含所有英雄和敌人角色
    /// </summary>
    public actor.TbCharacter TbCharacter {get; }
    public demo.Tbitem Tbitem {get; }
    public game.Tbconfig Tbconfig {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbReward = new demo.TbReward(loader("demo_tbreward"));
        TbCharacter = new actor.TbCharacter(loader("actor_tbcharacter"));
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        Tbconfig = new game.Tbconfig(loader("game_tbconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbReward.ResolveRef(this);
        TbCharacter.ResolveRef(this);
        Tbitem.ResolveRef(this);
        Tbconfig.ResolveRef(this);
    }
}

}
