
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public demo.TbReward TbReward {get; }
    /// <summary>
    /// 目录下包含所有英雄和敌人角色
    /// </summary>
    public actor.TbCharacter TbCharacter {get; }
    /// <summary>
    /// 英雄升级表
    /// </summary>
    public actor.TbHeroLevel TbHeroLevel {get; }
    /// <summary>
    /// 战斗内道具表
    /// </summary>
    public game.TbItem TbItem {get; }
    public game.Tbconfig Tbconfig {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbReward = new demo.TbReward(loader("demo_tbreward"));
        TbCharacter = new actor.TbCharacter(loader("actor_tbcharacter"));
        TbHeroLevel = new actor.TbHeroLevel(loader("actor_tbherolevel"));
        TbItem = new game.TbItem(loader("game_tbitem"));
        Tbconfig = new game.Tbconfig(loader("game_tbconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbReward.ResolveRef(this);
        TbCharacter.ResolveRef(this);
        TbHeroLevel.ResolveRef(this);
        TbItem.ResolveRef(this);
        Tbconfig.ResolveRef(this);
    }
}

}
