
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Tbhero
{
    private readonly System.Collections.Generic.Dictionary<int, hero> _dataMap;
    private readonly System.Collections.Generic.List<hero> _dataList;
    
    public Tbhero(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, hero>(count);
        _dataList = new System.Collections.Generic.List<hero>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            hero _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.hero.Deserializehero(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, hero> DataMap => _dataMap;
    public System.Collections.Generic.List<hero> DataList => _dataList;

    public hero GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public hero Get(int key) => _dataMap[key];
    public hero this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

