
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.unit
{ 
    public enum GroupType
    {
        /// <summary>
        /// 英雄
        /// </summary>
        Hero = 0,
        /// <summary>
        /// 敌人
        /// </summary>
        Enemy = 1,
    }

} 

