
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.actor
{
public sealed partial class Character : Luban.BeanBase
{
    public Character(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["group"].IsNumber) { throw new SerializationException(); }  Group = (unit.GroupType)_buf["group"].AsInt; }
        { if(!_buf["base_strength"].IsNumber) { throw new SerializationException(); }  BaseStrength = _buf["base_strength"]; }
        { if(!_buf["strength_bonuses"].IsNumber) { throw new SerializationException(); }  StrengthBonuses = _buf["strength_bonuses"]; }
        { if(!_buf["prefab"].IsString) { throw new SerializationException(); }  Prefab = _buf["prefab"]; }
    }

    public static Character DeserializeCharacter(JSONNode _buf)
    {
        return new actor.Character(_buf);
    }

    /// <summary>
    /// 索引键值
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly unit.GroupType Group;
    /// <summary>
    /// 基础力量
    /// </summary>
    public readonly float BaseStrength;
    /// <summary>
    /// 力量成长
    /// </summary>
    public readonly float StrengthBonuses;
    /// <summary>
    /// prefab_asset_key
    /// </summary>
    public readonly string Prefab;
   
    public const int __ID__ = -704271792;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "group:" + Group + ","
        + "baseStrength:" + BaseStrength + ","
        + "strengthBonuses:" + StrengthBonuses + ","
        + "prefab:" + Prefab + ","
        + "}";
    }
}
}

