
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.actor
{
public sealed partial class HeroLevel : Luban.BeanBase
{
    public HeroLevel(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["exp"].IsNumber) { throw new SerializationException(); }  Exp = _buf["exp"]; }
        { if(!_buf["strength"].IsNumber) { throw new SerializationException(); }  Strength = _buf["strength"]; }
        { if(!_buf["health_point"].IsNumber) { throw new SerializationException(); }  HealthPoint = _buf["health_point"]; }
        { if(!_buf["hp_regenration"].IsNumber) { throw new SerializationException(); }  HpRegenration = _buf["hp_regenration"]; }
    }

    public static HeroLevel DeserializeHeroLevel(JSONNode _buf)
    {
        return new actor.HeroLevel(_buf);
    }

    /// <summary>
    /// 索引键值
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 升级经验
    /// </summary>
    public readonly int Exp;
    /// <summary>
    /// 力量值
    /// </summary>
    public readonly float Strength;
    /// <summary>
    /// 最大血量
    /// </summary>
    public readonly float HealthPoint;
    /// <summary>
    /// 血量回复
    /// </summary>
    public readonly float HpRegenration;
   
    public const int __ID__ = 12367569;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "level:" + Level + ","
        + "exp:" + Exp + ","
        + "strength:" + Strength + ","
        + "healthPoint:" + HealthPoint + ","
        + "hpRegenration:" + HpRegenration + ","
        + "}";
    }
}
}

