
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.actor
{
/// <summary>
/// 目录下包含所有英雄和敌人角色
/// </summary>
public partial class TbCharacter
{
    private readonly System.Collections.Generic.Dictionary<string, actor.Character> _dataMap;
    private readonly System.Collections.Generic.List<actor.Character> _dataList;
    
    public TbCharacter(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, actor.Character>(count);
        _dataList = new System.Collections.Generic.List<actor.Character>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            actor.Character _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.actor.Character.DeserializeCharacter(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, actor.Character> DataMap => _dataMap;
    public System.Collections.Generic.List<actor.Character> DataList => _dataList;

    public actor.Character GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public actor.Character Get(string key) => _dataMap[key];
    public actor.Character this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

