
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.actor
{
/// <summary>
/// 英雄升级表
/// </summary>
public partial class TbHeroLevel
{
    private readonly System.Collections.Generic.List<actor.HeroLevel> _dataList;

    private System.Collections.Generic.Dictionary<(string, int), actor.HeroLevel> _dataMapUnion;

    public TbHeroLevel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<actor.HeroLevel>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            actor.HeroLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.actor.HeroLevel.DeserializeHeroLevel(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int), actor.HeroLevel>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Key, _v.Level), _v);
        }
    }

    public System.Collections.Generic.List<actor.HeroLevel> DataList => _dataList;

    public actor.HeroLevel Get(string key, int level) => _dataMapUnion.TryGetValue((key, level), out actor.HeroLevel __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

